var kswfobject=function(){function a(){if(!z){try{var c=m.getElementsByTagName("body")[0].appendChild(A("span"));c.parentNode.removeChild(c)}catch(e){return}z=true;c=I.length;for(var f=0;f<c;f++)I[f]()}}function b(c){if(z)c();else I[I.length]=c}function d(c){if(typeof s.addEventListener!=o)s.addEventListener("load",c,false);else if(typeof m.addEventListener!=o)m.addEventListener("load",c,false);else if(typeof s.attachEvent!=o)V(s,"onload",c);else if(typeof s.onload=="function"){var e=s.onload;s.onload=
function(){e();c()}}else s.onload=c}function j(){R?g():q()}function g(){var c=m.getElementsByTagName("body")[0],e=A(t);e.setAttribute("type",J);var f=c.appendChild(e);if(f){var h=0;(function(){if(typeof f.GetVariable!=o){var l=f.GetVariable("$version");if(l){l=l.split(" ")[1].split(",");i.pv=[parseInt(l[0],10),parseInt(l[1],10),parseInt(l[2],10)]}}else if(h<10){h++;setTimeout(arguments.callee,10);return}c.removeChild(e);f=null;q()})()}else q()}function q(){var c=K.length;if(c>0)for(var e=0;e<c;e++){var f=
K[e].id,h=K[e].callbackFn,l={success:false,id:f};if(i.pv[0]>0){var n=w(f);if(n)if(S(K[e].swfVersion)&&!(i.wk&&i.wk<312)){F(f,true);if(h){l.success=true;l.ref=u(f);h(l)}}else{B(n);h&&h(l)}}else{F(f,true);if(h){if((f=u(f))&&typeof f.SetVariable!=o){l.success=true;l.ref=f}h(l)}}}}function u(c){var e=null;if((c=w(c))&&c.nodeName=="OBJECT")if(typeof c.SetVariable!=o)e=c;else if(c=c.getElementsByTagName(t)[0])e=c;return e}function B(c){if(i.ie&&i.win&&c.readyState!=4){var e=A("div");c.parentNode.insertBefore(e,
c);e.parentNode.replaceChild(G(c),e);c.style.display="none";(function(){c.readyState==4?c.parentNode.removeChild(c):setTimeout(arguments.callee,10)})()}else c.parentNode.replaceChild(G(c),c)}function G(c){var e=A("div");if(i.win&&i.ie)e.innerHTML=c.innerHTML;else if(c=c.getElementsByTagName(t)[0])if(c=c.childNodes)for(var f=c.length,h=0;h<f;h++)!(c[h].nodeType==1&&c[h].nodeName=="PARAM")&&c[h].nodeType!=8&&e.appendChild(c[h].cloneNode(true));return e}function H(c,e,f){var h,l=w(f);if(i.wk&&i.wk<312)return h;
if(l){if(typeof c.id==o)c.id=f;if(i.ie&&i.win){var n="";for(var k in c)if(c[k]!=Object.prototype[k])if(k.toLowerCase()=="data")e.movie=c[k];else if(k.toLowerCase()=="styleclass")n+=' class="'+c[k]+'"';else if(k.toLowerCase()!="classid")n+=" "+k+'="'+c[k]+'"';k="";for(var p in e)if(e[p]!=Object.prototype[p])k+='<param name="'+p+'" value="'+e[p]+'" />';l.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+n+">"+k+"</object>";L[L.length]=c.id;h=w(c.id)}else{p=A(t);p.setAttribute("type",
J);for(n in c)if(c[n]!=Object.prototype[n])if(n.toLowerCase()=="styleclass")p.setAttribute("class",c[n]);else n.toLowerCase()!="classid"&&p.setAttribute(n,c[n]);for(var r in e)e[r]!=Object.prototype[r]&&r.toLowerCase()!="movie"&&C(p,r,e[r]);l.parentNode.replaceChild(p,l);h=p}}return h}function C(c,e,f){var h=A("param");h.setAttribute("name",e);h.setAttribute("value",f);c.appendChild(h)}function T(c){var e=w(c);if(e&&e.nodeName=="OBJECT")if(i.ie&&i.win){e.style.display="none";(function(){e.readyState==
4?W(c):setTimeout(arguments.callee,10)})()}else e.parentNode.removeChild(e)}function W(c){if(c=w(c)){for(var e in c)if(typeof c[e]=="function")c[e]=null;c.parentNode.removeChild(c)}}function w(c){var e=null;try{e=m.getElementById(c)}catch(f){}return e}function A(c){return m.createElement(c)}function V(c,e,f){c.attachEvent(e,f);D[D.length]=[c,e,f]}function S(c){var e=i.pv;c=c.split(".");c[0]=parseInt(c[0],10);c[1]=parseInt(c[1],10)||0;c[2]=parseInt(c[2],10)||0;return e[0]>c[0]||e[0]==c[0]&&e[1]>c[1]||
e[0]==c[0]&&e[1]==c[1]&&e[2]>=c[2]?true:false}function U(c,e,f,h){if(!(i.ie&&i.mac)){var l=m.getElementsByTagName("head")[0];if(l){f=f&&typeof f=="string"?f:"screen";if(h)Q=v=null;if(!v||Q!=f){h=A("style");h.setAttribute("type","text/css");h.setAttribute("media",f);v=l.appendChild(h);if(i.ie&&i.win&&typeof m.styleSheets!=o&&m.styleSheets.length>0)v=m.styleSheets[m.styleSheets.length-1];Q=f}if(i.ie&&i.win)v&&typeof v.addRule==t&&v.addRule(c,e);else v&&typeof m.createTextNode!=o&&v.appendChild(m.createTextNode(c+
" {"+e+"}"))}}}function F(c,e){if(X){e=e?"visible":"hidden";if(z&&w(c))w(c).style.visibility=e;else U("#"+c,"visibility:"+e)}}var o="undefined",t="object",J="application/x-shockwave-flash",s=window,m=document,x=navigator,R=false,I=[j],K=[],L=[],D=[],z=false,v,Q,X=true,i=function(){var c=typeof m.getElementById!=o&&typeof m.getElementsByTagName!=o&&typeof m.createElement!=o,e=x.userAgent.toLowerCase(),f=x.platform.toLowerCase(),h=f?/win/.test(f):/win/.test(e);f=f?/mac/.test(f):/mac/.test(e);e=/webkit/.test(e)?
parseFloat(e.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):false;var l=!+"\u000b1",n=[0,0,0],k=null;if(typeof x.plugins!=o&&typeof x.plugins["Shockwave Flash"]==t){if((k=x.plugins["Shockwave Flash"].description)&&!(typeof x.mimeTypes!=o&&x.mimeTypes[J]&&!x.mimeTypes[J].enabledPlugin)){R=true;l=false;k=k.replace(/^.*\s+(\S+\s+\S+$)/,"$1");n[0]=parseInt(k.replace(/^(.*)\..*$/,"$1"),10);n[1]=parseInt(k.replace(/^.*\.(.*)\s.*$/,"$1"),10);n[2]=/[a-zA-Z]/.test(k)?parseInt(k.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),
10):0}}else if(typeof s.ActiveXObject!=o)try{var p=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(p)if(k=p.GetVariable("$version")){l=true;k=k.split(" ")[1].split(",");n=[parseInt(k[0],10),parseInt(k[1],10),parseInt(k[2],10)]}}catch(r){}return{w3:c,pv:n,wk:e,ie:l,win:h,mac:f}}();(function(){if(i.w3){if(typeof m.readyState!=o&&m.readyState=="complete"||typeof m.readyState==o&&(m.getElementsByTagName("body")[0]||m.body))a();if(!z){typeof m.addEventListener!=o&&m.addEventListener("DOMContentLoaded",
a,false);if(i.ie&&i.win){m.attachEvent("onreadystatechange",function(){if(m.readyState=="complete"){m.detachEvent("onreadystatechange",arguments.callee);a()}});s==top&&function(){if(!z){try{m.documentElement.doScroll("left")}catch(c){setTimeout(arguments.callee,0);return}a()}}()}i.wk&&function(){z||(/loaded|complete/.test(m.readyState)?a():setTimeout(arguments.callee,0))}();d(a)}}})();(function(){i.ie&&i.win&&window.attachEvent("onunload",function(){for(var c=D.length,e=0;e<c;e++)D[e][0].detachEvent(D[e][1],
D[e][2]);c=L.length;for(e=0;e<c;e++)T(L[e]);for(var f in i)i[f]=null;i=null;for(var h in kswfobject)kswfobject[h]=null;kswfobject=null})})();return{embedSWF:function(c,e,f,h,l,n,k,p,r,M){var N={success:false,id:e};if(i.w3&&!(i.wk&&i.wk<312)&&c&&e&&f&&h&&l){F(e,false);b(function(){f+="";h+="";var E={};if(r&&typeof r===t)for(var y in r)E[y]=r[y];E.data=c;E.width=f;E.height=h;y={};if(p&&typeof p===t)for(var O in p)y[O]=p[O];if(k&&typeof k===t)for(var P in k)if(typeof y.flashvars!=o)y.flashvars+="&"+
P+"="+k[P];else y.flashvars=P+"="+k[P];if(S(l)){O=H(E,y,e);E.id==e&&F(e,true);N.success=true;N.ref=O}else F(e,true);M&&M(N)})}else M&&M(N)},ua:i,removeSWF:function(c){i.w3&&T(c)},createCSS:function(c,e,f,h){i.w3&&U(c,e,f,h)},addDomLoadEvent:b,addLoadEvent:d}}();function FABridge(a,b){this.target=a;this.remoteTypeCache={};this.remoteInstanceCache={};this.remoteFunctionCache={};this.localFunctionCache={};this.bridgeID=FABridge.nextBridgeID++;this.name=b;this.nextLocalFuncID=0;FABridge.instances[this.name]=this;FABridge.idMap[this.bridgeID]=this;return this}FABridge.TYPE_ASINSTANCE=1;FABridge.TYPE_ASFUNCTION=2;FABridge.TYPE_JSFUNCTION=3;FABridge.TYPE_ANONYMOUS=4;FABridge.initCallbacks={};FABridge.userTypes={};
FABridge.addToUserTypes=function(){for(var a=0;a<arguments.length;a++)FABridge.userTypes[arguments[a]]={typeName:arguments[a],enriched:false}};FABridge.argsToArray=function(a){for(var b=[],d=0;d<a.length;d++)b[d]=a[d];return b};FABridge.isArray=function(a){return!!a&&(a instanceof Array||Object.prototype.toString.call(a)==="[object Array]")};FABridge.isASProxy=function(a){return!!a&&(a instanceof ASProxy||!!a.bridgeName&&!!a.typeName&&a.className==="ASProxy")};
function instanceFactory(a){this.fb_instance_id=a;return this}function FABridge__invokeJSFunction(a){var b=a[0];a=a.concat();a.shift();return FABridge.extractBridgeFromID(b).invokeLocalFunction(b,a)}FABridge.addInitializationCallback=function(a,b){var d=FABridge.instances[a];if(d!=undefined)b.call(d);else{d=FABridge.initCallbacks[a];if(d==null)FABridge.initCallbacks[a]=d=[];d.push(b)}};
function FABridge__bridgeInitialized(a){var b=document.getElementsByTagName("object"),d=b.length,j=[];if(d>0)for(var g=0;g<d;g++)if(typeof b[g].SetVariable!="undefined")j[j.length]=b[g];d=document.getElementsByTagName("embed");g=d.length;b=[];if(g>0)for(var q=0;q<g;q++)if(typeof d[q].SetVariable!="undefined")b[b.length]=d[q];q=j.length;d=b.length;g="bridgeName="+a;if(q==1&&!d||q==1&&d==1)FABridge.attachBridge(j[0],a);else if(d==1&&!q)FABridge.attachBridge(b[0],a);else{var u=false;if(q>1)for(var B=
0;B<q;B++){for(var G=j[B].childNodes,H=0;H<G.length;H++){var C=G[H];if(C.nodeType==1&&C.tagName.toLowerCase()=="param"&&C.name.toLowerCase()=="flashvars"&&C.value.indexOf(g)>=0){FABridge.attachBridge(j[B],a);u=true;break}}if(u)break}if(!u&&d>1)for(j=0;j<d;j++)if(b[j].attributes.getNamedItem("flashVars").nodeValue.indexOf(g)>=0){FABridge.attachBridge(b[j],a);break}}return true}FABridge.nextBridgeID=0;FABridge.instances={};FABridge.idMap={};FABridge.refCount=0;
FABridge.extractBridgeFromID=function(a){return FABridge.idMap[a>>16]};FABridge.attachBridge=function(a,b){a=new FABridge(a,b);FABridge[b]=a;var d=FABridge.initCallbacks[b];if(d!=null){for(var j=0;j<d.length;j++)d[j].call(a);delete FABridge.initCallbacks[b]}};FABridge.blockedMethods={toString:true,get:true,set:true,call:true};
FABridge.prototype={root:function(){return this.deserialize(this.target.getRoot())},releaseASObjects:function(){return this.target.releaseASObjects()},releaseNamedASObject:function(a){return typeof a!="object"?false:this.target.releaseNamedASObject(a.fb_instance_id)},create:function(a){return this.deserialize(this.target.create(a))},makeID:function(a){return(this.bridgeID<<16)+a},getPropertyFromAS:function(a,b){if(FABridge.refCount>0)throw new Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");
else{FABridge.refCount++;retVal=this.target.getPropFromAS(a,b);retVal=this.handleError(retVal);FABridge.refCount--;return retVal}},setPropertyInAS:function(a,b,d){if(FABridge.refCount>0)throw new Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");else{FABridge.refCount++;retVal=this.target.setPropInAS(a,b,this.serialize(d));retVal=this.handleError(retVal);FABridge.refCount--;return retVal}},
callASFunction:function(a,b){if(FABridge.refCount>0)throw new Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");else{FABridge.refCount++;retVal=this.target.invokeASFunction(a,this.serialize(b));retVal=this.handleError(retVal);FABridge.refCount--;return retVal}},callASMethod:function(a,b,d){if(FABridge.refCount>0)throw new Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");
else{FABridge.refCount++;d=this.encodeJSON(this.serialize(d));retVal=this.target.invokeASMethod(a,b,d);retVal=this.handleError(retVal);FABridge.refCount--;return retVal}},invokeLocalFunction:function(a,b){var d;a=this.localFunctionCache[a];if(a!=undefined)d=this.serialize(a.apply(null,this.deserialize(b)));return d},getTypeFromName:function(a){return this.remoteTypeCache[a]},createProxy:function(a,b){b=this.getTypeFromName(b);instanceFactory.prototype=b;b=new instanceFactory(a);return this.remoteInstanceCache[a]=
b},getProxy:function(a){return this.remoteInstanceCache[a]},addTypeDataToCache:function(a){newType=new ASProxy(this,a.name);for(var b=a.accessors,d=0;d<b.length;d++)this.addPropertyToType(newType,b[d]);a=a.methods;for(d=0;d<a.length;d++)FABridge.blockedMethods[a[d]]==undefined&&this.addMethodToType(newType,a[d]);return this.remoteTypeCache[newType.typeName]=newType},addPropertyToType:function(a,b){var d=b.charAt(0),j;if(d>="a"&&d<="z"){j="get"+d.toUpperCase()+b.substr(1);d="set"+d.toUpperCase()+b.substr(1)}else{j=
"get"+b;d="set"+b}a[d]=function(g){this.bridge.setPropertyInAS(this.fb_instance_id,b,g)};a[j]=function(){return this.bridge.deserialize(this.bridge.getPropertyFromAS(this.fb_instance_id,b))}},addMethodToType:function(a,b){a[b]=function(){return this.bridge.deserialize(this.bridge.callASMethod(this.fb_instance_id,b,FABridge.argsToArray(arguments)))}},getFunctionProxy:function(a){var b=this;if(this.remoteFunctionCache[a]==null)this.remoteFunctionCache[a]=function(){b.callASFunction(a,FABridge.argsToArray(arguments))};
return this.remoteFunctionCache[a]},getFunctionID:function(a){if(a.__bridge_id__==undefined){a.__bridge_id__=this.makeID(this.nextLocalFuncID++);this.localFunctionCache[a.__bridge_id__]=a}return a.__bridge_id__},serialize:function(a){var b={},d=typeof a;if(d=="number"||d=="string"||d=="boolean"||d==null||d=="undefined")b=a;else if(FABridge.isArray(a)){b=[];for(d=0;d<a.length;d++)b[d]=this.serialize(a[d])}else if(d=="function"){b.type=FABridge.TYPE_JSFUNCTION;b.value=this.getFunctionID(a)}else if(FABridge.isASProxy(a)){b.type=
FABridge.TYPE_ASINSTANCE;b.value=a.fb_instance_id}else{b.type=FABridge.TYPE_ANONYMOUS;b.value=a}return b},deserialize:function(a){var b,d=typeof a;if(d=="number"||d=="string"||d=="boolean"||a==null||a==undefined)b=this.handleError(a);else if(FABridge.isArray(a)){b=[];for(d=0;d<a.length;d++)b[d]=this.deserialize(a[d])}else if(d=="object"){for(d=0;d<a.newTypes.length;d++)this.addTypeDataToCache(a.newTypes[d]);for(var j in a.newRefs)this.createProxy(j,a.newRefs[j]);if(a.type==FABridge.TYPE_PRIMITIVE)b=
a.value;else if(a.type==FABridge.TYPE_ASFUNCTION)b=this.getFunctionProxy(a.value);else if(a.type==FABridge.TYPE_ASINSTANCE)b=this.getProxy(a.value);else if(a.type==FABridge.TYPE_ANONYMOUS)b=a.value}return b},encodeJSON:function(a){var b,d,j,g="";switch(typeof a){case "object":if(a)if(FABridge.isArray(a)){for(d=0;d<a.length;++d){b=this.encodeJSON(a[d]);if(g)g+=",";g+=b}return"["+g+"]"}else if(typeof a.toString!="undefined"){for(d in a){b=a[d];if(typeof b!="undefined"&&typeof b!="function"){b=this.encodeJSON(b);
if(g)g+=",";g+=this.encodeJSON(d)+":"+b}}return"{"+g+"}"}return"null";case "number":return isFinite(a)?""+a:"null";case "string":j=a.length;g='"';for(d=0;d<j;d+=1){b=a.charAt(d);if(b>=" "){if(b=="\\"||b=='"')g+="\\";g+=b}else switch(b){case "\u0008":g+="\\b";break;case "\u000c":g+="\\f";break;case "\n":g+="\\n";break;case "\r":g+="\\r";break;case "\t":g+="\\t";break;default:b=b.charCodeAt();g+="\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}}return g+'"';case "boolean":return""+a;default:return"null"}},
addRef:function(a){this.target.incRef(a.fb_instance_id)},release:function(a){this.target.releaseRef(a.fb_instance_id)},handleError:function(a){if(typeof a=="string"&&a.indexOf("__FLASHERROR")==0){a=a.split("||");FABridge.refCount>0&&FABridge.refCount--;throw new Error(a[1]);}else return a}};ASProxy=function(a,b){this.bridge=a;this.typeName=b;this.className="ASProxy";return this};
ASProxy.prototype={get:function(a){return this.bridge.deserialize(this.bridge.getPropertyFromAS(this.fb_instance_id,a))},set:function(a,b){this.bridge.setPropertyInAS(this.fb_instance_id,a,b)},call:function(a,b){this.bridge.callASMethod(this.fb_instance_id,a,b)},addRef:function(){this.bridge.addRef(this)},release:function(){this.bridge.release(this)}};function KongregateAPI(){this.initialize()}
KongregateAPI.prototype={initialize:function(){this._flashVarsString="";this._flashVarsObject={};this._services={};this._apiLoadedCallback=null;this._paramsReceived=false;var a=location.search.split("?")[1];if(a){a=a.split("&");for(var b=0;b<a.length;b++){var d=a[b].split("=");d&&d.length==2&&this.processParam(d[0],d[1])}}if(this._postMessageParams=!this.flashVarsObject().kongregate_ansible_path&&top!=window){var j=this;window.addEventListener("message",function(g){if(j.messageOriginIsKongregate(g)){g=
g.data;g.type=="params"&&j.handleParamsMessage(g.data)}});top.postMessage("kongregate_request_params","*")}else this._paramsReceived=true},processParam:function(a,b){if(a.indexOf("kongregate")==0){this._flashVarsObject[a]=b;this._flashVarsString+=a+"="+b+"&"}},flashVarsString:function(){return this._flashVarsString},flashVarsObject:function(){return this._flashVarsObject},getVariable:function(a){return this._flashVarsObject[a]},messageOriginIsKongregate:function(a){var b=this._flashVarsObject.kongregate_host;
return b&&a.origin=="http://"+b||a.origin=="https://"+b},loadAPI:function(a){if(!this._postMessageParams||this.paramsReceived())this.doLoadAPI(a);else this._apiLoadedCallback=a},handleParamsMessage:function(a){if(!this.paramsReceived()){for(var b in a)this.processParam(b,a[b]);this._paramsReceived=true;this._apiLoadedCallback&&this.doLoadAPI(this._apiLoadedCallback)}},paramsReceived:function(){return this._paramsReceived},doLoadAPI:function(a){var b=this,d=function(){for(var j=FABridge.ansible.root(),
g=["services","stats","mtx","chat","sharedContent"],q=0;q<g.length;q++){var u=g[q];b._services[u]=j.getServices(u)}typeof a=="function"&&a()};kswfobject.addDomLoadEvent(function(){b.createAnsible(d)})},getAPI:function(){return this._services},embedFrame:function(a,b){b=b?b:"contentdiv";b=document.getElementById(b);var d="<iframe id='content' frameborder='0' ";d+="style='position:relative;top:0px;left:0px;";d+="border:0px none;padding:0px;width:"+b.offsetWidth+"px;height:"+b.offsetHeight+"px;'";d+=
"src='"+a+"'></iframe>";b.innerHTML=d},createAnsible:function(a){FABridge.addInitializationCallback("ansible",a);a=document.createElement("div");a.id="ansible_container";a.style.position="absolute";a.style.width=a.style.height="1px";a.style.left=a.style.top="-1000px";document.body.appendChild(a);var b=document.createElement("div");b.id="ansible";a.appendChild(b);a={bridgeName:"ansible",json_encode:"true"};for(var d in this.flashVarsObject())a[d]=this.flashVarsObject()[d];if((d=decodeURIComponent(this.getVariable("kongregate_ansible_path")))&&
d.indexOf("http://")!=0)d=location.protocol=="https:"&&d.indexOf("chat.kongregate.com")==0?"https://"+d.replace("chat.kongregate.com","ssl.kongcdn.com"):"http://"+d;kswfobject.embedSWF(d,"ansible","1","1","9.0.0",null,a,{allowScriptaccess:"always"},null,null)}};kongregateAPI=new KongregateAPI;
